Repository Jatin-Shihora/DSA-Essentials, pull requests merged in 2022-10, with the labels that each got.

#1 Job Sequencing in Java
  Algorithms/Greedy/Job Sequencing/jobSequencing.java
Labels: hacktoberfest-accepted, Java, greedy

#3 Stack Implementation using Linked List
  Data_Structures/Stack/Implementation/StackUsingLL.java
Labels: good first issue, hacktoberfest-accepted, Java

#9 Bubblesort.js
  Algorithms/Sorting/Bubble_Sort/BubbleSort.js
Labels: enhancement, hacktoberfest-accepted

#12 Create Matrice_Add_Sub.java
  Data_Structures/Array/2-D Array/Matrice_Add_Sub.java
Labels: good first issue, hacktoberfest-accepted

#15 Implementation of BucketSort Algorithm in Javascript
  Algorithms/Sorting/Bucket_Sort/BucketSort.js
Labels: enhancement, hacktoberfest-accepted

#17 Matrix Spiral Traversal- Added
  Data_Structures/Array/2-D Array/SpiralTraversalMatrix.java
Labels: hacktoberfest-accepted, Java, beginner

#18 Implementation of Binary Insertion Sort in C++
  Algorithms/Sorting/Binary_Insertion_Sort/BinaryInsertionSort.cpp
Labels: hacktoberfest-accepted, beginner

#20 Added Doubly Linked List with various functions
  Data_Structures/LinkedList/Doubly_Linked_List/DoublyLinkedList.java
Labels: Java, intermediate

#22 Added Bucket Sort algorithm using C#
  Algorithms/Sorting/Bucket_Sort/BucketSort.cs
Labels: hacktoberfest-accepted, intermediate

#23 Enhancement + Class name fix
  Algorithms/DP/nth_ugly_number/Nth_Ugly_Number.java
Labels: enhancement, hacktoberfest-accepted, Java

#25 Class name fix + enhancement.
  Algorithms/Backtracking/StringPermute/StringPermute.java
Labels: enhancement, hacktoberfest-accepted, Java, refactoring

#27 Added MYSQL as a part of CoreCS
  Mysql/README.md
Labels: enhancement, hacktoberfest-accepted, intermediate

#28 Added ComputerNetworks as a part of CS fundamentals
  Computer Networks/README.md
Labels: enhancement, hacktoberfest-accepted, intermediate

#29 Added CloudComputing as a part of Core CS
  Cloud Computing/Pics/Service_models.png
  Cloud Computing/README.md
Labels: enhancement, hacktoberfest-accepted, intermediate

#30 Added SlidingWindow algo with practice problems
  Algorithms/Sliding Window/10. Equivalent sub arrays.cpp
  Algorithms/Sliding Window/2. first neg element of size k.cpp
  Algorithms/Sliding Window/3. Sliding window max.cpp
  Algorithms/Sliding Window/4. Count anagrams.cpp
  Algorithms/Sliding Window/5. count distnict elements in each window.cpp
  Algorithms/Sliding Window/6. count the no of subarrays in given range.cpp
  Algorithms/Sliding Window/7. Subarray Product less than K.cpp
  Algorithms/Sliding Window/8. Smallest window containing 012.cpp
  Algorithms/Sliding Window/9. Max points you can obtain from cards.cpp
  Algorithms/Sliding Window/README.md
Labels: enhancement, hacktoberfest-accepted, intermediate

#31 Added Trie with examples
  Data_Structures/Trie/1. insert and search.cpp
  Data_Structures/Trie/README.md
Labels: enhancement, hacktoberfest-accepted, intermediate

#32 Added Priority Queue with examples
  Data_Structures/Priority Queue/1.Find the Original Array from Doubled array.java
  Data_Structures/Priority Queue/10. Lucy neighbours.cpp
  Data_Structures/Priority Queue/11. Construct Target array with mutliple sums.cpp
  Data_Structures/Priority Queue/2. Array of Doubled pairs.java
  Data_Structures/Priority Queue/4. Binary tree levels in sorted order.cpp
  Data_Structures/Priority Queue/6. Find K pairs with smallest sums.cpp
  Data_Structures/Priority Queue/7. Sort elements by frequency.cpp
  Data_Structures/Priority Queue/8. Task Scheduler.cpp
  Data_Structures/Priority Queue/9. Course Scheduler 3.cpp
  Data_Structures/Priority Queue/README.md
  Data_Structures/Priority Queue/images/task.png
Labels: enhancement, hacktoberfest-accepted, intermediate

#33 Added OOPS concept in CPP
  C-CPP-OOPS/README.md
  C-CPP-OOPS/memory-layout-C.jpg
  C-CPP-OOPS/shallow-copy-deep-copy.jpg
Labels: enhancement, hacktoberfest-accepted, intermediate

#34 Added concepts of DBMS
  DBMS/Mysql/README.md
  DBMS/README.md
Labels: enhancement, hacktoberfest-accepted, intermediate

#35 Added TC of sorting algos
  Algorithms/Sorting/time-space-complexity-of-sorting-algos.md
Labels: enhancement, hacktoberfest-accepted, intermediate

#36 Added CN
  Computer Networks/Computer-Networks-for-Interviews/README.md
  Computer Networks/Computer-Networks-for-Interviews/images/image1.png
  Computer Networks/Computer-Networks-for-Interviews/images/image10.png
  Computer Networks/Computer-Networks-for-Interviews/images/image11.png
  Computer Networks/Computer-Networks-for-Interviews/images/image12.png
  Computer Networks/Computer-Networks-for-Interviews/images/image13.png
  Computer Networks/Computer-Networks-for-Interviews/images/image14.png
  Computer Networks/Computer-Networks-for-Interviews/images/image15.png
  Computer Networks/Computer-Networks-for-Interviews/images/image16.png
  Computer Networks/Computer-Networks-for-Interviews/images/image17.png
  Computer Networks/Computer-Networks-for-Interviews/images/image18.png
  Computer Networks/Computer-Networks-for-Interviews/images/image19.png
  Computer Networks/Computer-Networks-for-Interviews/images/image2.png
  Computer Networks/Computer-Networks-for-Interviews/images/image20.png
  Computer Networks/Computer-Networks-for-Interviews/images/image21.png
  Computer Networks/Computer-Networks-for-Interviews/images/image22.png
  Computer Networks/Computer-Networks-for-Interviews/images/image23.png
  Computer Networks/Computer-Networks-for-Interviews/images/image24.png
  Computer Networks/Computer-Networks-for-Interviews/images/image25.png
  Computer Networks/Computer-Networks-for-Interviews/images/image26.png
  Computer Networks/Computer-Networks-for-Interviews/images/image27.png
  Computer Networks/Computer-Networks-for-Interviews/images/image28.png
  Computer Networks/Computer-Networks-for-Interviews/images/image29.png
  Computer Networks/Computer-Networks-for-Interviews/images/image3.png
  Computer Networks/Computer-Networks-for-Interviews/images/image30.png
  Computer Networks/Computer-Networks-for-Interviews/images/image4.png
  Computer Networks/Computer-Networks-for-Interviews/images/image5.png
  Computer Networks/Computer-Networks-for-Interviews/images/image6.png
  Computer Networks/Computer-Networks-for-Interviews/images/image7.png
  Computer Networks/Computer-Networks-for-Interviews/images/image8.png
  Computer Networks/Computer-Networks-for-Interviews/images/image9.png
Labels: enhancement, hacktoberfest-accepted, intermediate
